name: Build and Deploy Gitbook
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build üîß
        run: |
          echo "Fixing graceful-fs issue cb.apply"
          npm install graceful-fs@latest --save
          echo "Installing Gitbook CLI"
          sudo npm install gitbook-cli -g
          echo "Changing directory to gitbook"
          cd gitbook
          echo "Installing Gitbook Plugins"
          gitbook install
          echo "Building Gitbook"
          gitbook build . ../build
          echo "Removing node_modules directory"
          git clean -fx node_modules

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.4.8
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
